### ISSUE TITLE
OpenATV 6.3, 'Allow subtitle language to equal audio language' reseting itself to 'none'

### ISSUE THREAD

**Issue by ghost** [openatv/enigma2#1204]
Hi
This setting in Audio Options is always reseting itself to 'none' after reboot/shutdown, this disables subtitles for all channels that have same audio language.

I tried several times enabling to 'English' (to match English audio, useful for non native English speakers) but it always resets to 'none' after reboot.

**Comment by thawtes** [comment]
This option (Allow subtitle language to equal audio language ) works automatically.
no need to adjust here!

**Comment by Tony-il-Capo** [comment]
How?.. Can you explain?

I have prefer audio language 1: PT; audio 2 EN; Sub language 1: PT, Sub 2 EN
but I have subtitles disabled in most channels **if this option is set to 'none'** (because audio language match subtitle language) 

If I set this option manually (EN) then STB always enables subtitles even if language match audio (what I want)

**Comment by thawtes** [comment]
> 
> 
> How?.. Can you explain?
> 
> I have prefer audio language 1: PT; audio 2 EN; Sub language 1: PT, Sub 2 EN
> but I have subtitles disabled in most channels **if this option is set to 'none'** (because audio language match subtitle language)
> 
> If I set this option manually (EN) then STB always enables subtitles even if language match audio (what I want)

prefer is
audio language1: PT 2:EN
Sub language 1: PT, Sub 2 EN

if have channel audio PT; selected audio lang PT , selected subtitle lang EN... such works

exactly which pairing do you want?

**Comment by thawtes** [comment]
for example

prefer audio lang 1 = PT
prefer audio lang 2 = EN
prefer audio lang 3 = None
prefer audio lang 4 = None

prefer subtitle lang 1 = PT
prefer subtitle lang 2 = None
prefer subtitle lang 3 = None
prefer subtitle lang 4 = None

channel have PT Audio
AudioLang work = PT
SubtitleLang work = Not Work

channel have EN Audio
AudioLang work = EN
SubtitleLang work = PT

OK? Did you understand ?

**Comment by Tony-il-Capo** [comment]
OK... yes, thanks, but, just to be more clear...

I need EN subs when there's EN audio (all channels)
Prefer audio lang 1 = PT
Prefer audio lang 2 = EN
Prefer sub lang 1 = PT
Prefer sub lang 2 = EN
For channels with PT audio subs are mostly unavailable 
'Prefer subtitles stored by service' is set to 'yes'.

For your information, it always worked before until recently, no changes were made to user settings, subs were automatically selected (not sure what has changed)

Then it stopped working and I realized the option 'Allow subtitle language to equal audio language', description of this option matched the behavior I was seeing, so setting that to'English' makes instant effect and subtitles I want get enabled automatically (for EN audio + EN subs)

Like you say, other options like 'allow subtitles for hearing impaired' may force to enable/show them anyway.

But, shouldn't 'Allow subtitle language to equal audio language' option  keep user setting instead of defaulting to 'none'? Because this option actually works like I explained above, but it's lost after reboot.
Also, this option suits better my situation because I can choose to ignore PT subs ((by choosing 'English', instead of PT+EN) 

And, excuse my ignorance on this, but aren't sub tracks for hearing impaired different from 'regular' subs, so maybe using 'allow subtitles for hearing impaired'=yes, is unwanted for my case? I've seen channels with those subs, very descriptive, not sure if system can distinguish between them...

Sorry for the long text.

**Comment by thawtes** [comment]
it was nothing, you're welcome..

your choices
Prefer audio lang 1 = PT
Prefer audio lang 2 = EN
Prefer sub lang 1 = PT
Prefer sub lang 2 = EN

Allow subtitle language to equal audio language = None mean = 2

for EN audio work + EN subtitle work choose with IR left rigth button
Allow subtitle language to equal audio language = PT,EN

after adjust your all settings closewith Green Button
otherwise the settings are not saved !

I hope I could help

**Comment by Tony-il-Capo** [comment]
>Allow subtitle language to equal audio language = None mean = 2

Actually 'none' = 0
Checked with OpenWebif (inspect network activity)
`http://vuduo2ip/api/saveconfig?key=config.autolanguage.equal_languages&value=0`

'English' = 2
`http://vuduo2ip/api/saveconfig?key=config.autolanguage.equal_languages&value=2`
> for EN audio work + EN subtitle work choose with IR left rigth button
> Allow subtitle language to equal audio language = PT,EN

> **after adjust your all settings close with Green Button
> otherwise the settings are not saved !**

Of course I did that, even checked the settings file, I can see there config.autolanguage.equal_languages=2 , after reboot it disappears.

The workaround I got working a few days ago is applying this setting via shell script just after enigma2 startup using web api, 
`curl --noproxy '*' --data value=2 "http://127.0.0.1/api/saveconfig?key=config.autolanguage.equal_languages"`

**Comment by Tony-il-Capo** [comment]
This [commit](https://github.com/openatv/enigma2/commit/50035d88db99d953fb1825accb23d3245ccbbcd3) changed Selection Behavior related to your [issue](https://github.com/openatv/enigma2/issues/1100) @thawtes 

Can't fully understand everything, maybe something is wrong/missing there...

**Comment by thawtes** [comment]
> 
> 
> This [commit](https://github.com/openatv/enigma2/commit/50035d88db99d953fb1825accb23d3245ccbbcd3) changed Selection Behavior related to your [issue](https://github.com/openatv/enigma2/issues/1100) @thawtes
> 
> Can't fully understand everything, maybe something is wrong/missing there...

something wrong or not missing..

this code has changed and functionally automatic  (actually the same)
`config.autolanguage.equal_languages = ConfigSelection(default = "15", choices = [
		("0", _("None")),("1", "1"),("2", "2"),("3", "1,2"),
		("4", "3"),("5", "1,3"),("6", "2,3"),("7", "1,2,3"),
		("8", "4"),("9", "1,4"),("10", "2,4"),("11", "1,2,4"),
		("12", "3,4"),("13", "1,3,4"),("14", "2,3,4"),("15", _("All"))])`

so there is nothing wrong
