### ISSUE TITLE
LocationsBox, Unterschied oatv 7.0 zu 7.1

### ISSUE THREAD

**Issue by Anskar71** [openatv/enigma2#2636]
In der LocationsBox im EMC unter "Datei verschieben" gibt es einen Unterschied oatv 7.0 zu 7.1.
Bei oatv 7.0 ist man gleich oben wo der Pfad gewählt wird.
In oatv 7.1 muß ich erst mit Steuerkreuz Taste links nach oben wechseln, warum?
In oatv 7.0 ist das schon immer so das man gleich oben ist, bei oatv 7.1 gab es da eine Änderung, mit Image vom 20.09.22 ging es noch und mit Image vom 06.10.22 ist es anderst.
Also muß diese Änderung zwischen 20.09. und 06.10.22 liegen.
Wäre schön wenn das wieder zurück geschraubt wird.
![Metrix_7 0](https://user-images.githubusercontent.com/116512415/198238114-32d94c25-d204-4ee5-becb-ee93574a1ef1.jpg)
![Metrix_7 1](https://user-images.githubusercontent.com/116512415/198238122-8af2781b-efe8-45ed-8cf8-9a475b405e5e.jpg)
![Metrix_EMC](https://user-images.githubusercontent.com/116512415/198238127-3b8f9a81-cf95-42b1-81d9-41cf7b1228ab.jpg)

**Comment by jbleyel** [comment]
Das ist Absicht, denn die meisten User nutzten eher die Bookmarks.

**Comment by IanSav** [comment]
I am using Google Translate to understand this post.  Sorry if I have not understood your issue correctly.

I think you are saying that the position of the cursor in the file list does not always start at the top of the list.  You need to use the UP button to step back to the first entry.  If this is the issue you are reporting then I have fixed this for the next version of FileList.py where the issue was caused.

**Comment by jbleyel** [comment]
That's not the problem.
The initial selection is now the bookmark list and not the directory list like in the old code.
That's why you need to switch to the directory list first.


But if you have define your target directory as bookmark you do not need to browse in your directory tree.
This is much faster by the way.

**Comment by Anskar71** [comment]
Ich möchte nicht allgemein was als Lesezeichen setzen sondern nur mal temporär einen Film verschiebe, also von A nach B.
Da geht das oben definitiv schneller.
Also wie es früher war.
Das gleiche wenn man im EMC ein Symlink erstellen will, da ist das genauso unsinnig wie es neu ist.
