### ISSUE TITLE
[Video Wizard] Sort by highest res/quality

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#2897]
Sort video to highest resolution/progressive/interleaved.

eg: 
1080p
1080i
720p
720i
etc...

![screenshot](https://github.com/openatv/enigma2/assets/9741693/ec275d50-5e71-47d0-abab-d3a00376e92a)

**Comment by jbleyel** [comment]
I think that’s not a bug. The sort order is the most common used order based on the possible valid resolutions. 

720p needs to be the first because not all TV have more than 720p

**Comment by IanSav** [comment]
In older days one might even suggest that we start at 480i/576i and then work our way up to the higher resolutions.  These days I think 720p is a fairly safe bet.

**Comment by wedebe** [comment]
Ah, that makes sense.

However... in the case where e2 has done a detection to get available modes, surrely it then _knows_ the max capable resolution?

**Comment by Papi2000-new** [comment]
If EDID could be read correctly, that will work. But it's not sure, that it could be retreived in all cases.
Also if you have choosen 2160p-multi at an UHD-TV, and plug the box to a FHD-TV, you will not get a picture after the bootlogo has passed, because there also is no auto-limit to the max. capable available resolution.

**Comment by jbleyel** [comment]
The Video Wizard has been changed.
