### ISSUE TITLE
Hang with more than 25pfs IPTV streams

### ISSUE THREAD

**Issue by jeepcook** [openatv/enigma2#2916]
**Describe the bug / Actual behaviour:**
The 30fps or 50fps h265 iptv streams are freezing or jerking. No problem with 25fps streams.
This was ok with 7.2 OATV version. as usually gstreamer is unable to play correctly iptv streams so I'm using exteplayer3 or gstplayer.

An example of stream (4k 30fps stream), Love Nature 4K from Samsung TV:
https://d18dyiwu97wm6q.cloudfront.net/v1/master/3722c60a815c199d9c0ef36c5b73da68a62b09d1/LoveNature4K2-prod/playlist.m3u8?ads.device_did=%7BPSID%7D&ads.device_dnt=%7BTARGETOPT%7D&ads.us_privacy=1YNY&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.ssai=SSSLIVE

**Expected behaviour:**
fluidity

**Has this issue started to happen just recently?**
Yes with 7.3 version. No bug with 7.2.

**To reproduce:**
Just play stream

**Screenshots**
NA

**Image/Box Model (please complete the following information):**
 - Version: 7.3
 - BoxModel: SF8008

**Additional context**
Is more evident with 50pfs streams but I can't give urls here, they are private

**Comment by jeepcook** [comment]
See the full discussion here: https://www.opena.tv/openatv-7-3-py3-11-openssl-3-1-a/63225-openatv-7-3-hang-h265-avc-50fps-iptv-streams.html

In fact the new gstreamer is enabled by default and was responsible of my hang problems. But in the settings screen it is tag as no. So I had to enable it, save, and disable it to solve my problems. 
It's confusing and may cause not understandable problems like I met.

**Comment by 4l3x2k** [comment]
Please set the refresh rate to "multi" or "auto" in your picture settings and test the playback again. 30 frames per second at 50 Hz usually causes problems.

From my point of view, the stream runs smoothly here with the "auto" refresh rate.

The "Enable new GStreamer playback" setting actually has nothing to do with this. However, this should preferably be set to "No" since the new display has not yet been fully implemented.

SF8008 @ openATV 7.3

**Comment by jeepcook** [comment]
My configuration has always been 1080p 50kz from OATV 6.2 to 7.2. And this problem appears with 7.3 with exactly the same configuration. What is the problem, my configuration or OATV 7.3?

**Comment by jeepcook** [comment]
Did you test with 50fps iptv streams? I can't give you stream urls.

**Comment by 4l3x2k** [comment]
No. I did not test with 50fps streams because I  do not have any source.

Can you record this kind of stream to provide an test file?
Even. Does the record file play without any hangs and freezes via  EMC, MC, MediaPlayer if you can record it?

**Comment by 4l3x2k** [comment]
Ohhh yes ... the stream is hanging!

But the reason is clear because I download something with another device. The download makes the video "hanging" and "freezing" of course.

**Comment by 4l3x2k** [comment]
Could you please download the test videos: [Testvideos](https://fotovideotec.de/frameraten/downloads/ft-standard.zip)

Report any hangs or freezes.

This is all because your environment seems to be special.

**Comment by jeepcook** [comment]
I don't understand everything you wrote, you speak about hang when you download, it's not the problem... 
I will do the test this evening. But my environment has nothing special because I did a clean and fresh installation.

**Comment by 4l3x2k** [comment]
@jeepcook 
Any news here? Do these local videos play back fluently?

If you've tested with a clean image (without restore anything), then it may hang or freeze because something else in your network is downloading something.
This situation resulted in hangs and freezes for me.

**Comment by jeepcook** [comment]
Hello,

Rebuilt all my tv lists to use gstreamer instead of exteplayer3 or gstplayer. I have a lot of 50fps or 25fps stable streams.
I need exteplayer3 or gstplayer for m3u8 streams (hls), unable to open them with gstreamer.

How to know which gstreamer version is running, old or new, because in the oatv information we only have the 1.22.3 version. 

I'm running other tests.

Thanks

**Comment by 4l3x2k** [comment]
Thank you for feedback.

I can't imagine how this 25, 30 and 60 look like. Does the picture jitter? Does your TV any picture optimizations?
A hang would be clear to me. Video and Audio stops and continiues after a time. But fluidity is hard to imagine. There is at least almost always a small difference that you can see. That's the reason why threre are different frame rates.
Is it possible that you record the behaiviour with a camera if can't post urls?

HLS (M3U8) is the only adaptive streaming protocol that works best with gstreamer. DASH (MPD) has problems we're trying to overcome by gstreamers playbin3 instead of playbin element.
The switch in the settings menu to use "new gstreamer" enables playbin3 instead of playbin. That is meant with "new".

gstreamer 1.22.3 is the latest stable bugfix release for gstreamer and is the same for the switch "new gstreamer" (playbin3) and playbin in the settings menu.

**Comment by jeepcook** [comment]
I've not watched full videos you sent me. But for what I watched the picture doesn't jitter, and above all with my streams there are now no problems with 90% of them, I have to verify other streams.  I have no optimisation in my TV, this one begins to be old (Samsung UE40C6000).

How to verify if it's playbin or playbin3 which is running? I can't find running processes with these names, and I can't find playbin or playbin3 when I do a find / -name....

For hls, you said gstreamer is the best, so I have to do more tests because exteplayer3 and gstplayer have problems with hls urls. In fact I'm using hls m3u8 urls for Pluto TV and Samsung TV plateforms channels.

To conclude, with these tests and new configurations my opinion has completely changed about gstreamer.

to be continued... ;-))

**Comment by 4l3x2k** [comment]
There are three options to verify playbin or playbin3 is used:
1. trust the settings
2. enable gstreamer debug log in settings (leave it with default else it may producde huge files at 700 MB)
3. enable gstreamer pipeline graph (creates a .dot file you can convert -offline or online- to svg or picture formats like png)

2. and 3. can be enabled in the log settings menu and the files are stored in the debug log folder (defaults to /home/root/log).
Be aware that the options are more suited to developers and hardcore testers that want to know whats goiing on under the hood.

You can't find playbin(3) because these are no programs nor unix processes. They are executed in gstreamer within enigma2's process context. playbin(3) is a gstreamer element to create gstreamer pipelines.
If you want to "find / -name" them you're going to look for "playback" in gstreamer's base plug-ins.

**Comment by jeepcook** [comment]
Ok thanks for your explanation. You told yesterday that gstreamer can handle hls streams. Could you please explain me why this doesn't work? No picture displayed.

#SERVICE 1:0:1:dee4:d7e0:e0e3:1010101:0:0:1:https%3a//i.mjh.nz/PlutoTV/5f8ecd336d64c9000754cdf1-alt.m3u8
#DESCRIPTION The Pet Collective

**Comment by 4l3x2k** [comment]
Set "Enable new GStreamer playback" in settings menu to off. It is not fully implemented yet!

Both streams work for me.

You should also use 4097 instead of 1 in the first field of "#SERVICE ...".

And please. What is required by you to close this issue? If we're going on in this style of communication we'll talk until the end of the year and on!

If you want to discuss or share your experience please use the forum.

**Comment by jeepcook** [comment]
Thanks, yes I can now close the issue. But don't forget that for a fresh installation new gstreamer is tagged as off but is in reality on. So this was the origin of the issue. I had to enable it, save and disable it to have my stream ok with exteplayer3 and gstplayer.

Now I will use gstreamer a soon as it works for all my streams and open a discussion about gstreamer streams bugs.

Thanks a lot for your help!
