### ISSUE TITLE
LCDPicon Renderer

### ISSUE THREAD

**Issue by jbleyel** [openatv/enigma2#3100]
The LCDPicon Renderer find not all picons like the Picon Renderer.
The LCDPicon should be a subclass of Picon.

**Comment by AbuBaniaz** [comment]
It should really import the names from the image's picon renderer.

**Comment by Papi2000-new** [comment]
not really. You may have a set of colorful picons for the gui skin. but on boxes with only bw-display it may be helpfull, to have a set of simple designed picons for that simple displays. 
Therefore the set for displays can be a sub-set of the gui picons (folder picon_lcd within the folder picon), or at the same level as /picon

**Comment by jbleyel** [comment]
You miss the point, there is a difference in the picon name calculation routine of these 2 renderer.
This means the picon will not displayed with LCDPicon but it will displayed with Picon.

**Comment by AbuBaniaz** [comment]
Name of picon, not location of picon. ATV/Vix and whoever has forked from them allow people to have one set of picon for OSD and another set for front panel display (LCD).

On Vix, there is a separate picon renderer for the front panel display /LCD picon. It used to separately derive the picon name, Simon capewell changed it so it derives/imports the name from the picon renderer. I'll post link to commit later.

I think ATV still does same thing (work out lcd/front panel display picon name separately). Actually, I think lots of skins do the same thing (work out picon name separately). Possibly why SNPicons not as popular for ATV users. Been a while since I checked, so apologies in advance if incorrect.
