### ISSUE TITLE
Matrix FHD by default 

### ISSUE THREAD

**Issue by Insprion80** [openatv/enigma2#3184]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

MATRIX SKIN 

One of the best skins across the history of enigma2, I hope to give it more time and effort to upgrade it to recent features. 

1. Majority of plugins now depend on fhd skin, although fhd feature available now but is it possible to make FHD version is the default and user who want to use it in HD, he can switch it as he want.
2. Posters support, even with presence of moded versions of Matrix skin with posters but I hope you modify it to deal with posters directly without use 3rd party modifications, presence of posters very important to users to track the incoming events with epg in different languages. 
3. Can you add rounded corners to Matrix skin? 
4. Add different shapes for infobar. 

There are a lot of stuff you can add,

Regards

**Comment by jbleyel** [comment]
Hello @Insprion80 ,

You may mean MetrixHD and this is here -> https://github.com/openatv/MetrixHD

1.  The default will be HD and not FHD this is by purpose and we have no plan to change this.
2. Poster support needs a lot of changes in enigma core because it makes no sense to implement this in MetrixHD only.
3. NO . The major design of MetrixHD is flat and not rounded.
If you like rounded edges then you need to choose a different skin or create a user skin.
4. You can create skinparts.
