### ISSUE TITLE
OpenATV 6.1 EMC/MediaPlayer aspect ratio problem (>16:9 not displayed in letterbox)

### ISSUE THREAD

**Issue by ghost** [openatv/enigma2#784]
Hi
There's seems to be a problem with aspect ratio in EMC/MediaPlayer, movie files with aspect ratio 2:35:1 (or wider) are displayed in full 16:9 screen, picture is being stretched, pretty disturbing.

To understand it, movie files with 2:35:1 aspect ratio should be displayed with black bars on top and bottom in a 16:9 screen.

AV setting for aspect ratio (wider than) >16:9 is set to "letterbox"
If you toggle this setting for something else and then back to "letterbox" then aspect ratio is correct when watching movies in EMC/MediadPlayer.
Rebooting makes the problem to happen again.

As I understand AV settings for aspect ratio is not being stored in settings file.

Probably related to [568](https://github.com/openatv/enigma2/issues/568)

Hope someone can take a look at this.
Box is a Vu+ Duo2 running latest OpenATV 6.1

Thanks.

**Comment by s3n0** [comment]
Hello.

Everything is fine for me - Formuler F3 / OpenATV 6.1 (night-build version approx. 2018-01). If I change the ">16:9" setting in the A / V configuration via MENU OpenATV to "Pan&Scan", then wide EMC videos (2.35:1) are magnified correctly on the 16:9 screen. Of course, keeping the aspect ratio. The video is displayed as it should be - without black boxes at the top and bottom.

This setting is stored in the file:
**/etc/enigma2/settings.xml**
...under this item:
**config.av.policy_169=panscan**
...so you can check it too. The value of "panscan" works at least in my case. 

Alternatively, you can try backing up your "settings.xml" file and then deleting it - this deletes all basic enigma settings.

It would be best to try a clean flash image and then test to see if this problem persists with the "view content > 16:9" configuration. It looks like a conflict problem in the "settings.xml" file (for example, old configuration data from previous versions of OpenATV). But I'm not still an expert on the Enigma2, so take it as my tip unless you've always solved your problem ;-).

**Comment by Tony-il-Capo** [comment]
Letterbox doesn't work until you set it again after boot, either by UI menu or by command
`echo -n letterbox > /proc/stb/video/policy2`

Note that 'letterbox' is already set but does not work until you set it again.

This is a 'known' bug for some STBs like Vu+, and as far as I know, nothing has been done to fix it.
See [here]( https://www.opena.tv/openatv-6-1-image-rueckmeldungen/36565-16-9-wider-movies-aspect-ratio-fix-workaround.html?highlight=aspect+ratio)

I have the above command run at boot and then everything is fine.

**Comment by s3n0** [comment]
Why do not you use Pan & Scan? It works for me - as I described above.

**Comment by Tony-il-Capo** [comment]
... panscan cuts sides from the video (for >16:9 content), it's ridiculous really! We want full picture with **original aspect**, not full screen with left and right cropped. And like I said 'letterbox' AR works but you have to re-set it at every reboot.

**Comment by s3n0** [comment]
If you do not have a cinema-movie projector in your home, it is useless. All movies are made today with regard to HOME TV KINO, which means 16:9 video format. Wide formats are for cinema-screen projection (designed for commercial theaters).

It's your thing, of course I do not want you to throw away.

I personally mind very much that I gave 2000EUR for SmartTV 16:9 to my home and that I do not watch movies on the full screen for which I paid, but only about 80% of the total screen area. Why do you want to watch a small compressed video (original aspect ratio) when you can watch a bigger video (16:9) ?

If it was a difference between 16: 9 and 4: 3, then I admit it's stupid. But in the case of commercial theaters and home theaters, there is not such a big difference.

**Comment by Tony-il-Capo** [comment]
> but only about 80% of the total screen area

You're wasting about 20% of lateral picture anyway, when you use panscan on wide formats -> 16:9.

> when you can watch a **bigger video** ?

More like a zoomed video.


btw, I would never pay 2000€ for a  (not very) smarttv!
And finally, we got away from the original issue, that was, "letterbox" AR for wide movies should work as intended.

**Comment by s3n0** [comment]
I do not own your set top box to track Python code. Just download a file from GitHub server, edit it for debugging (just test the code you need). You place the file in the appropriate directory in the set top box and test it, for example, with the command: `python -i AVSwitch.py` ​​(CTRL + B to end the debugger).

You could turn on at least DebugLOG in OpenATV and then send a dump (/home/root/logs). You may also see an error about why your set top box will not be set to Letterbox mode after rebooting.

I do not own the same device, I'm not an OpenATV developer, so I can not help. It takes a lot of free time and you have at home a set top box like you do. Then I do not have to be an OpenATV developer and I will solve the problem - if I understand at least a bit about IT. Otherwise, only the OpenATV developer will really help you, who knows the OpenATV code. However, I do not have an OpenATV developer. I would have to trace the code manually. Look for a bug in it and, of course, the device on which the problem occurs.

If I assume the correct, clean installation of OpenATV has already tried and did not help.

**Comment by s3n0** [comment]
I just add some info to refine the BUG report. 

Discussion on the problem is already on the forum (topic started by Tony-il-Capo):
https://www.opena.tv/openatv-6-1-image-rueckmeldungen/36565-16-9-wider-movies-aspect- ratio-fix-workaround.html

There is also a download of the bash-script file created by Tony, as a temporary solution to the problem.

A temporary solution is basically to send a "letterbox" status to the video decoder configuration:
`echo -n letterbox > /proc/stb/video/policy2`

**Comment by s3n0** [comment]
I just add some info to refine the BUG report.

Discussion on the problem is already on the forum (topic started by Tony-il-Capo): https://www.opena.tv/openatv-6-1-image-rueckmeldungen/36565-16-9-wider-movies-aspect-ratio-fix-workaround.html

There is also a download of the bash-script file created by Tony-il-Capo, as a temporary solution to the problem.

A temporary solution is basically to send the "letterbox" status to the video decoder configuration after each boot of Enigma:
`echo -n letterbox > /proc/stb/video/policy2`

**Comment by Tony-il-Capo** [comment]
Hi @s3n0 
I'm running OpenATV 6.3 on my Vu+Duo2 and I still have this issue.

After that thread on opena.tv I modified my workaround to be more reliable when applying the fix (no need to adjust sleep time) ... but the solution is basically the same.

**Comment by jbleyel** [comment]
We have refactored the video mode settings.
Please reopen with more details if the issue still exists.
